# Generated by Django 5.0.6 on 2025-09-15 11:33

from django.db import migrations
from django.utils.text import slugify


def add_hasilinvest_categories(apps, schema_editor):
    """Add new categories for HasilInvest blog"""
    Category = apps.get_model('blog', 'Category')
    
    # Define all categories including existing and new ones
    categories_data = [
        # Original categories
        {'name': 'Technology', 'description': 'Technology and programming articles', 'order': 1},
        {'name': 'Lifestyle', 'description': 'Personal development and lifestyle tips', 'order': 2},
        {'name': 'Business', 'description': 'Business and entrepreneurship insights', 'order': 3},
        {'name': 'Education', 'description': 'Learning and educational content', 'order': 4},
        {'name': 'Health & Wellness', 'description': 'Health and wellness advice', 'order': 5},
        {'name': 'Islamic Banking', 'description': 'Islamic banking principles and practices', 'order': 6},
        {'name': 'Islamic Finance', 'description': 'Islamic financial instruments and markets', 'order': 7},
        {'name': 'Banking in Islam', 'description': 'Islamic banking concepts and Shariah compliance', 'order': 8},
        {'name': 'Financial Advice', 'description': 'Personal and Islamic financial guidance', 'order': 9},
        
        # New HasilInvest categories
        {'name': 'Personal Finance', 'description': 'Personal financial planning and money management', 'order': 10},
        {'name': 'Investing', 'description': 'Investment strategies and market insights', 'order': 11},
        {'name': 'Stock Market', 'description': 'Stock market analysis and trading insights', 'order': 12},
        {'name': 'Halal Investments', 'description': 'Shariah-compliant investment opportunities', 'order': 13},
        {'name': 'Real Estate', 'description': 'Real estate investment and market trends', 'order': 14},
        {'name': 'Entrepreneurship', 'description': 'Starting and growing your own business', 'order': 15},
        {'name': 'Career Development', 'description': 'Professional growth and career advancement', 'order': 16},
        {'name': 'Startups', 'description': 'Startup culture, funding, and innovation', 'order': 17},
        {'name': 'Innovation', 'description': 'Latest trends and innovative ideas', 'order': 18},
        {'name': 'Productivity', 'description': 'Tips and tools for increased productivity', 'order': 19},
        {'name': 'Leadership', 'description': 'Leadership skills and management insights', 'order': 20},
        {'name': 'Motivation', 'description': 'Motivational content and personal growth', 'order': 21},
        {'name': 'Mindset', 'description': 'Mental frameworks for success and growth', 'order': 22},
        {'name': 'Economy', 'description': 'Economic analysis and market trends', 'order': 23},
        {'name': 'Global Markets', 'description': 'International markets and global economics', 'order': 24},
        {'name': 'Tax & Zakat', 'description': 'Tax planning and Islamic Zakat guidance', 'order': 25},
        {'name': 'Retirement Planning', 'description': 'Planning for a secure financial future', 'order': 26},
        {'name': 'Wealth Management', 'description': 'Strategies for building and preserving wealth', 'order': 27},
        {'name': 'Crypto & Blockchain (Halal perspective)', 'description': 'Cryptocurrency and blockchain from Islamic viewpoint', 'order': 28},
        {'name': 'Sustainability & Green Finance', 'description': 'Sustainable investing and green financial products', 'order': 29},
    ]
    
    # Create categories that don't exist
    for cat_data in categories_data:
        category, created = Category.objects.get_or_create(
            name=cat_data['name'],
            defaults={
                'slug': slugify(cat_data['name']),
                'description': cat_data['description'],
                'order': cat_data['order'],
                'is_active': True,
                'meta_title': cat_data['name'],
                'meta_description': cat_data['description'][:160],
            }
        )
        if created:
            print(f"Created category: {cat_data['name']}")


def reverse_add_categories(apps, schema_editor):
    """Reverse migration - remove only the new categories, keep original ones"""
    Category = apps.get_model('blog', 'Category')
    
    # Only remove the new categories, not the original ones
    new_categories = [
        'Personal Finance', 'Investing', 'Stock Market', 'Halal Investments', 
        'Real Estate', 'Entrepreneurship', 'Career Development', 'Startups',
        'Innovation', 'Productivity', 'Leadership', 'Motivation', 'Mindset',
        'Economy', 'Global Markets', 'Tax & Zakat', 'Retirement Planning',
        'Wealth Management', 'Crypto & Blockchain (Halal perspective)', 
        'Sustainability & Green Finance'
    ]
    
    Category.objects.filter(name__in=new_categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_excerpt_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.RunPython(add_hasilinvest_categories, reverse_add_categories),
    ]
